run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck    # Vérifie que les erreurs sont gérées (obligatoire en Go)
    - gosimple    # Suggère des simplifications
    - govet       # Analyse statique standard
    - ineffassign # Détecte les assignations inutiles
    - staticcheck # Un linter très puissant
    - typecheck   # Vérifie la cohérence des types
    - unused      # Détecte le code mort (variables/fonctions non utilisées)
    - funlen      # INTERDIT les fonctions trop longues (Max 60 lignes)
    - gocyclo     # Vérifie la complexité (Pas trop de if/else imbriqués)

linters-settings:
  funlen:
    lines: 60           # Une fonction > 60 lignes = Erreur
    statements: 40      # Une fonction > 40 instructions = Erreur
  gocyclo:
    min-complexity: 15  # Seuil de complexité
  errcheck:
    check-type-assertions: false  # sync.Map type assertions are safe by design
    check-blank: false            # _ = expr is explicit acknowledgment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Test files: allow ignoring errors with _ (common Go test pattern)
    - path: "_test\\.go"
      linters:
        - errcheck
        - funlen
        - gocyclo
    # SSE/HTTP write errors are non-actionable (client disconnect)
    - path: "notifications/handler\\.go"
      linters:
        - errcheck
    # templ Render errors are propagated via http.ResponseWriter
    - text: "Render"
      linters:
        - errcheck
    # CLI commands: defer Close on DB/server is standard Go CLI pattern
    - path: "cmd/"
      linters:
        - errcheck
        - funlen
        - gocyclo
    # import/importer.go: complex parsing logic is inherently cyclomatic
    - path: "import/importer\\.go"
      linters:
        - gocyclo
        - funlen
    # scanner/: AST scanning and code generation are inherently complex
    - path: "scanner/"
      linters:
        - gocyclo
        - funlen
    # views/generics/helpers.go: functions called from templ-generated code
    - path: "views/generics/helpers\\.go"
      linters:
        - unused
    # engine/panel.go Router: wiring function, complexity is structural
    - path: "engine/panel\\.go"
      text: "Router"
      linters:
        - gocyclo
    # validation/messages.go: map literals are inherently long, not real complexity
    - path: "validation/messages\\.go"
      linters:
        - funlen
    # validation/rules.go: ParseRules is a large switch — inherent to DSL parsing
    - path: "validation/rules\\.go"
      linters:
        - gocyclo
    # validation/custom.go: RegisterValidation errors are non-actionable (panic on bad tag)
    - path: "validation/custom\\.go"
      linters:
        - errcheck
    # export/exporter.go: excelize API returns errors for invalid cell refs only
    - path: "export/exporter\\.go"
      linters:
        - errcheck
        - funlen
    # jobs/: sync.Map type assertions are safe by construction
    - path: "jobs/"
      linters:
        - errcheck
    # middleware/: recovery/ratelimit patterns are standard
    - path: "middleware/"
      linters:
        - errcheck
    # staticcheck SA5011: false positive — nil check is done before use
    - linters:
        - staticcheck
      text: "SA5011"
    # appconfig/loader.go: setDefaults is a config table, not real complexity
    - path: "appconfig/loader\\.go"
      linters:
        - funlen
    # search/global_search.go: GlobalSearch orchestrates multiple providers
    - path: "search/global_search\\.go"
      linters:
        - funlen
    # validation/rules.go: ParseRules is a DSL switch, statements count is misleading
    - path: "validation/rules\\.go"
      linters:
        - funlen
    # ui/layouts: primaryColorPalette used from templ-generated code
    - path: "ui/layouts/"
      linters:
        - unused