// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package widgets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/bozz33/sublimego/widget"
)

func Chart(w *widget.ChartWidget) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"p-6 bg-white border border-gray-100 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700\"><div class=\"mb-4\"><h3 class=\"text-lg font-medium leading-6 text-gray-900 dark:text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(w.Label)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/widgets/chart.templ`, Line: 11, Col: 13}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h3></div><div class=\"relative w-full\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("height: " + w.Height + "px")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/widgets/chart.templ`, Line: 14, Col: 67}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><div id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(w.ID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/widgets/chart.templ`, Line: 15, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"></div></div><script>\n\t\t\t(function() {\n\t\t\t\tconst options = {\n\t\t\t\t\tseries: JSON.parse('{ w.GetSeriesJSON() }'),\n\t\t\t\t\tchart: {\n\t\t\t\t\t\ttype: '{ string(w.Type) }',\n\t\t\t\t\t\theight: { w.Height },\n\t\t\t\t\t\tfontFamily: 'Inter, sans-serif',\n\t\t\t\t\t\ttoolbar: { show: false },\n\t\t\t\t\t\tbackground: 'transparent'\n\t\t\t\t\t},\n\t\t\t\t\tcolors: JSON.parse('{ w.GetColorsJSON() }'),\n\t\t\t\t\tstroke: {\n\t\t\t\t\t\tcurve: 'smooth',\n\t\t\t\t\t\twidth: 2\n\t\t\t\t\t},\n\t\t\t\t\tdataLabels: { enabled: false },\n\t\t\t\t\txaxis: {\n\t\t\t\t\t\tcategories: JSON.parse('{ w.GetLabelsJSON() }'),\n\t\t\t\t\t\taxisBorder: { show: false },\n\t\t\t\t\t\taxisTicks: { show: false },\n\t\t\t\t\t\tlabels: {\n\t\t\t\t\t\t\tstyle: { colors: '#6b7280', fontSize: '12px' }\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\tgrid: {\n\t\t\t\t\t\tborderColor: '#e5e7eb',\n\t\t\t\t\t\tstrokeDashArray: 4,\n\t\t\t\t\t},\n\t\t\t\t\tplotOptions: {\n\t\t\t\t\t\tpie: {\n\t\t\t\t\t\t\tdonut: {\n\t\t\t\t\t\t\t\tsize: '70%',\n\t\t\t\t\t\t\t\tlabels: { show: true, total: { show: true, label: 'Total' } }\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\tlabels: JSON.parse('{ w.GetLabelsJSON() }')\n\t\t\t\t};\n\n\t\t\t\tif (document.querySelector('#{ w.ID }')) {\n\t\t\t\t\tconst chart = new ApexCharts(document.querySelector('#{ w.ID }'), options);\n\t\t\t\t\tchart.render();\n\t\t\t\t}\n\t\t\t})();\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
