// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozz33/sublimego/internal/ent/notification"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *NotificationCreate) SetUserID(v string) *NotificationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *NotificationCreate) SetBody(v string) *NotificationCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableBody(v *string) *NotificationCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *NotificationCreate) SetLevel(v string) *NotificationCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableLevel(v *string) *NotificationCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *NotificationCreate) SetIcon(v string) *NotificationCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableIcon(v *string) *NotificationCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetActionURL sets the "action_url" field.
func (_c *NotificationCreate) SetActionURL(v string) *NotificationCreate {
	_c.mutation.SetActionURL(v)
	return _c
}

// SetNillableActionURL sets the "action_url" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableActionURL(v *string) *NotificationCreate {
	if v != nil {
		_c.SetActionURL(*v)
	}
	return _c
}

// SetActionLabel sets the "action_label" field.
func (_c *NotificationCreate) SetActionLabel(v string) *NotificationCreate {
	_c.mutation.SetActionLabel(v)
	return _c
}

// SetNillableActionLabel sets the "action_label" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableActionLabel(v *string) *NotificationCreate {
	if v != nil {
		_c.SetActionLabel(*v)
	}
	return _c
}

// SetRead sets the "read" field.
func (_c *NotificationCreate) SetRead(v bool) *NotificationCreate {
	_c.mutation.SetRead(v)
	return _c
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableRead(v *bool) *NotificationCreate {
	if v != nil {
		_c.SetRead(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationCreate) SetCreatedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreatedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.Level(); !ok {
		v := notification.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Read(); !ok {
		v := notification.DefaultRead
		_c.mutation.SetRead(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Notification.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Notification.level"`)}
	}
	if _, ok := _c.mutation.Read(); !ok {
		return &ValidationError{Name: "read", err: errors.New(`ent: missing required field "Notification.read"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(notification.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.ActionURL(); ok {
		_spec.SetField(notification.FieldActionURL, field.TypeString, value)
		_node.ActionURL = value
	}
	if value, ok := _c.mutation.ActionLabel(); ok {
		_spec.SetField(notification.FieldActionLabel, field.TypeString, value)
		_node.ActionLabel = value
	}
	if value, ok := _c.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
		_node.Read = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
