// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bozz33/sublimego/internal/ent/notification"
	"github.com/bozz33/sublimego/internal/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdate) SetUserID(v string) *NotificationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableUserID(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdate) SetBody(v string) *NotificationUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableBody(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NotificationUpdate) ClearBody() *NotificationUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetLevel sets the "level" field.
func (_u *NotificationUpdate) SetLevel(v string) *NotificationUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableLevel(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *NotificationUpdate) SetIcon(v string) *NotificationUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIcon(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *NotificationUpdate) ClearIcon() *NotificationUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetActionURL sets the "action_url" field.
func (_u *NotificationUpdate) SetActionURL(v string) *NotificationUpdate {
	_u.mutation.SetActionURL(v)
	return _u
}

// SetNillableActionURL sets the "action_url" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableActionURL(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetActionURL(*v)
	}
	return _u
}

// ClearActionURL clears the value of the "action_url" field.
func (_u *NotificationUpdate) ClearActionURL() *NotificationUpdate {
	_u.mutation.ClearActionURL()
	return _u
}

// SetActionLabel sets the "action_label" field.
func (_u *NotificationUpdate) SetActionLabel(v string) *NotificationUpdate {
	_u.mutation.SetActionLabel(v)
	return _u
}

// SetNillableActionLabel sets the "action_label" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableActionLabel(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetActionLabel(*v)
	}
	return _u
}

// ClearActionLabel clears the value of the "action_label" field.
func (_u *NotificationUpdate) ClearActionLabel() *NotificationUpdate {
	_u.mutation.ClearActionLabel()
	return _u
}

// SetRead sets the "read" field.
func (_u *NotificationUpdate) SetRead(v bool) *NotificationUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(notification.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(notification.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(notification.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.ActionURL(); ok {
		_spec.SetField(notification.FieldActionURL, field.TypeString, value)
	}
	if _u.mutation.ActionURLCleared() {
		_spec.ClearField(notification.FieldActionURL, field.TypeString)
	}
	if value, ok := _u.mutation.ActionLabel(); ok {
		_spec.SetField(notification.FieldActionLabel, field.TypeString, value)
	}
	if _u.mutation.ActionLabelCleared() {
		_spec.ClearField(notification.FieldActionLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdateOne) SetUserID(v string) *NotificationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableUserID(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdateOne) SetBody(v string) *NotificationUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableBody(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NotificationUpdateOne) ClearBody() *NotificationUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetLevel sets the "level" field.
func (_u *NotificationUpdateOne) SetLevel(v string) *NotificationUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableLevel(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *NotificationUpdateOne) SetIcon(v string) *NotificationUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIcon(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *NotificationUpdateOne) ClearIcon() *NotificationUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetActionURL sets the "action_url" field.
func (_u *NotificationUpdateOne) SetActionURL(v string) *NotificationUpdateOne {
	_u.mutation.SetActionURL(v)
	return _u
}

// SetNillableActionURL sets the "action_url" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableActionURL(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetActionURL(*v)
	}
	return _u
}

// ClearActionURL clears the value of the "action_url" field.
func (_u *NotificationUpdateOne) ClearActionURL() *NotificationUpdateOne {
	_u.mutation.ClearActionURL()
	return _u
}

// SetActionLabel sets the "action_label" field.
func (_u *NotificationUpdateOne) SetActionLabel(v string) *NotificationUpdateOne {
	_u.mutation.SetActionLabel(v)
	return _u
}

// SetNillableActionLabel sets the "action_label" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableActionLabel(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetActionLabel(*v)
	}
	return _u
}

// ClearActionLabel clears the value of the "action_label" field.
func (_u *NotificationUpdateOne) ClearActionLabel() *NotificationUpdateOne {
	_u.mutation.ClearActionLabel()
	return _u
}

// SetRead sets the "read" field.
func (_u *NotificationUpdateOne) SetRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(notification.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(notification.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(notification.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.ActionURL(); ok {
		_spec.SetField(notification.FieldActionURL, field.TypeString, value)
	}
	if _u.mutation.ActionURLCleared() {
		_spec.ClearField(notification.FieldActionURL, field.TypeString)
	}
	if value, ok := _u.mutation.ActionLabel(); ok {
		_spec.SetField(notification.FieldActionLabel, field.TypeString, value)
	}
	if _u.mutation.ActionLabelCleared() {
		_spec.ClearField(notification.FieldActionLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(notification.FieldRead, field.TypeBool, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
