// Code generated by SublimeGo Scanner. DO NOT EDIT.
// Generated at: 2026-02-02 00:31:46
// Resources found: 1

package registry

import (
	"github.com/bozz33/SublimeGo/internal/resources/user"

	"github.com/bozz33/SublimeGo/pkg/engine"
)

// AllResources contains all discovered resources.
var AllResources = []engine.Resource{

	&user.UserResource{}, // internal\resources\user\resource.go

}

// ResourceCount returns the number of registered resources.
func ResourceCount() int {
	return 1
}

// GetResourceBySlug returns a resource by its slug.
func GetResourceBySlug(slug string) (engine.Resource, bool) {
	for _, resource := range AllResources {
		if resource.Slug() == slug {
			return resource, true
		}
	}
	return nil, false
}

// HasResource checks if a resource with the given slug exists.
func HasResource(slug string) bool {
	_, exists := GetResourceBySlug(slug)
	return exists
}

// GetAllSlugs returns all resource slugs.
func GetAllSlugs() []string {
	slugs := make([]string, 0, len(AllResources))
	for _, resource := range AllResources {
		slugs = append(slugs, resource.Slug())
	}
	return slugs
}

// ResourceInfo contains metadata about a resource.
type ResourceInfo struct {
	Slug        string
	Label       string
	PluralLabel string
	Icon        string
}

// GetResourceInfo returns metadata for all resources.
func GetResourceInfo() []ResourceInfo {
	info := make([]ResourceInfo, 0, len(AllResources))
	for _, resource := range AllResources {
		info = append(info, ResourceInfo{
			Slug:        resource.Slug(),
			Label:       resource.Label(),
			PluralLabel: resource.PluralLabel(),
			Icon:        resource.Icon(),
		})
	}
	return info
}

// RegistryStats contains statistics about the registry.
type RegistryStats struct {
	TotalResources int
	TotalConflicts int
	TotalWarnings  int
	GeneratedAt    string
}

// GetStats returns registry statistics.
func GetStats() RegistryStats {
	return RegistryStats{
		TotalResources: 1,
		TotalConflicts: 0,
		TotalWarnings:  0,
		GeneratedAt:    "2026-02-02 00:31:46",
	}
}
