// Code generated by SublimeGo Scanner. DO NOT EDIT.
// Generated at: 2026-02-04 06:57:00
// Resources found: 0
// Pages found: 0

package registry

import (
	"github.com/bozz33/sublimego/engine"
)

// AllResources contains all discovered resources.
// This slice is automatically generated by the SublimeGo scanner.
var AllResources = []engine.Resource{}

// AllPages contains all discovered custom pages.
// This slice is automatically generated by the SublimeGo scanner.
var AllPages = []engine.Page{}

// PageCount returns the number of registered pages.
func PageCount() int {
	return 0
}

// GetPageBySlug returns a page by its slug.
func GetPageBySlug(slug string) (engine.Page, bool) {
	for _, page := range AllPages {
		if page.Slug() == slug {
			return page, true
		}
	}
	return nil, false
}

// HasPage checks if a page with the given slug exists.
func HasPage(slug string) bool {
	_, exists := GetPageBySlug(slug)
	return exists
}

// GetAllPageSlugs returns all page slugs.
func GetAllPageSlugs() []string {
	slugs := make([]string, 0, len(AllPages))
	for _, page := range AllPages {
		slugs = append(slugs, page.Slug())
	}
	return slugs
}

// PageInfo contains metadata about a page.
type PageInfo struct {
	Slug  string
	Label string
	Icon  string
	Group string
}

// GetPageInfo returns metadata for all pages.
func GetPageInfo() []PageInfo {
	info := make([]PageInfo, 0, len(AllPages))
	for _, page := range AllPages {
		info = append(info, PageInfo{
			Slug:  page.Slug(),
			Label: page.Label(),
			Icon:  page.Icon(),
			Group: page.Group(),
		})
	}
	return info
}

// ResourceCount returns the number of registered resources.
func ResourceCount() int {
	return 0
}

// GetResourceBySlug returns a resource by its slug.
func GetResourceBySlug(slug string) (engine.Resource, bool) {
	for _, resource := range AllResources {
		if resource.Slug() == slug {
			return resource, true
		}
	}
	return nil, false
}

// HasResource checks if a resource with the given slug exists.
func HasResource(slug string) bool {
	_, exists := GetResourceBySlug(slug)
	return exists
}

// GetAllSlugs returns all resource slugs.
func GetAllSlugs() []string {
	slugs := make([]string, 0, len(AllResources))
	for _, resource := range AllResources {
		slugs = append(slugs, resource.Slug())
	}
	return slugs
}

// ResourceInfo contains metadata about a resource.
type ResourceInfo struct {
	Slug        string
	Label       string
	PluralLabel string
	Icon        string
}

// GetResourceInfo returns metadata for all resources.
func GetResourceInfo() []ResourceInfo {
	info := make([]ResourceInfo, 0, len(AllResources))
	for _, resource := range AllResources {
		info = append(info, ResourceInfo{
			Slug:        resource.Slug(),
			Label:       resource.Label(),
			PluralLabel: resource.PluralLabel(),
			Icon:        resource.Icon(),
		})
	}
	return info
}

// RegistryStats contains statistics about the registry.
type RegistryStats struct {
	TotalResources int
	TotalConflicts int
	TotalWarnings  int
	GeneratedAt    string
}

// GetStats returns registry statistics.
func GetStats() RegistryStats {
	return RegistryStats{
		TotalResources: 1,
		TotalConflicts: 0,
		TotalWarnings:  0,
		GeneratedAt:    "2026-02-02 00:31:46",
	}
}
